import { 
  HERO_BLOCK_QUERY, 
  HEADER_BLOCK_QUERY,
  FEATURE_BLOCK_QUERY,
  FEATURE_CARDS_BLOCK_QUERY,
  FEATURES_MINIMAL_BLOCK_QUERY,
  CALL_TO_ACTION_BLOCK_QUERY,
  LOGO_BLOCK_QUERY,
  TESTIMONIAL_BLOCK_QUERY,
  FREEFORM_BLOCK_QUERY,
  PORTABLE_TEXT_BLOCK_QUERY,
  BLOG_ARCHIVE_BLOCK_QUERY,
  SERVICES_BLOCK_QUERY,
  FORM_BLOCK_QUERY,
  MEDIA_BLOCK_QUERY,
} from "./blocks";

export const pageBuilder = `
  pageBuilder[] {
    ${HERO_BLOCK_QUERY},
    ${HEADER_BLOCK_QUERY},
    ${FEATURE_BLOCK_QUERY},
    ${FEATURE_CARDS_BLOCK_QUERY},
    ${FEATURES_MINIMAL_BLOCK_QUERY},
    ${CALL_TO_ACTION_BLOCK_QUERY},
    ${LOGO_BLOCK_QUERY},
    ${TESTIMONIAL_BLOCK_QUERY},
    ${FREEFORM_BLOCK_QUERY},
    ${PORTABLE_TEXT_BLOCK_QUERY},
    ${BLOG_ARCHIVE_BLOCK_QUERY},
    ${SERVICES_BLOCK_QUERY},
    ${FORM_BLOCK_QUERY},
    ${MEDIA_BLOCK_QUERY}
  }
`