import { 
  heroBlockQuery, 
  headerBlockQuery,
  heroClickthroughBlockQuery,
  featureBlockQuery,
  featureCardsBlockQuery,
  featuresMinimalBlockQuery,
  callToActionBlockQuery,
  logoBlockQuery,
  testimonialBlockQuery,
  freeformBlockQuery,
  portableTextBlockQuery,
  blogArchiveBlockQuery,
  servicesBlockQuery,
  formBlockQuery,
  mediaBlockQuery,
  simpleCardBlockQuery,
  featuredTestimonialBlockQuery,
  comparisonTableBlockQuery,
  testimonialCarouselBlockQuery,
  heroSectionBlockQuery,
  stepProcessBlockQuery,
  clickthroughTopicBlockQuery,
  stepRightImageBlockQuery,
  iconListBlockQuery,
  iconListTwoColumnBlockQuery,
  iconHighlightBlockQuery,
  pricingBlockQuery,
  caseStudyGridBlockQuery,
  itToolsCardBlockQuery,
  socialReviewBlockQuery,
  accordionAndImageBlockQuery,
  frequentlyAskedQuestionBlockQuery,
  joinOurNewsletterBlockQuery,
  avatarWithDetailsQuery
} from "./blocks";

//ABCD Add 5 component name here for type-script auto generate
export const pageBuilder = `
  pageBuilder[] {
    ${heroBlockQuery},
    ${headerBlockQuery},
    ${featureBlockQuery},
    ${featureCardsBlockQuery},
    ${featuresMinimalBlockQuery},
    ${callToActionBlockQuery},
    ${logoBlockQuery},
    ${testimonialBlockQuery},
    ${freeformBlockQuery},
    ${portableTextBlockQuery},
    ${blogArchiveBlockQuery},
    ${servicesBlockQuery},
    ${formBlockQuery},
    ${mediaBlockQuery},

    ${heroClickthroughBlockQuery},
    ${simpleCardBlockQuery},
    ${featuredTestimonialBlockQuery},
    ${comparisonTableBlockQuery},
    ${testimonialCarouselBlockQuery},
    ${heroSectionBlockQuery},
    ${stepProcessBlockQuery},
    ${clickthroughTopicBlockQuery},
    ${stepRightImageBlockQuery},
    ${iconListBlockQuery},
    ${iconListTwoColumnBlockQuery},
    ${iconHighlightBlockQuery},
    ${pricingBlockQuery},
    ${caseStudyGridBlockQuery},
    ${itToolsCardBlockQuery},
    ${socialReviewBlockQuery},
    ${accordionAndImageBlockQuery},
    ${frequentlyAskedQuestionBlockQuery},
    ${joinOurNewsletterBlockQuery},
    ${avatarWithDetailsQuery}
  }
`